var sweety ="sweety";
var cuttie ="cutie";
console.log("Before swap..");
console.log(sweety, cuttie);
var temp="sawety";
sweety=cuttie;
cuttie=temp;
console.log("After swap..");
console.log(sweety,cuttie);
var num1="100";
var num2="200";
var num3="300";
console.log("Before swap..");
console.log(num1,num2,num3);
num1=num2;
var temp="200";
num2=temp;
num2=num3;
var temp="100";
